table Visitas_Cliques
    lineageTag: e5f6g7h8-0004

    column Data
        dataType: dateTime
        formatString: dd/mm/yyyy
        sourceColumn: Date

    column Visitas
        dataType: int64
        formatString: #,##0
        sourceColumn: Visits

    column Cliques
        dataType: int64
        formatString: #,##0
        sourceColumn: Clicks

    measure 'Total Visitas ao Perfil' = SUM(Visitas_Cliques[Visitas])
        formatString: #,##0
        description: "Total de visitas de usuários ao perfil."

    measure 'Total Cliques no Link' = SUM(Visitas_Cliques[Cliques])
        formatString: #,##0
        description: "Total de cliques no link da bio."

    measure 'Taxa Conversao Bio %' = DIVIDE([Total Cliques no Link], [Total Visitas ao Perfil], 0)
        formatString: 0.00%
        description: "Porcentagem de visitantes do perfil que clicaram no link da bio."

    partition Visitas_Cliques-Partition = m
        mode: import
        source =
            let
                PathVisits = pDataBasePath & "\" & pAccountName & "\Visits.csv",
                SourceVisits = Csv.Document(File.Contents(PathVisits), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                #"HeadersVisits" = Table.PromoteHeaders(SourceVisits, [PromoteAllScalars=true]),
                #"TypeVisits" = Table.TransformColumnTypes(#"HeadersVisits",{{"Date", type date}, {"Visits", Int64.Type}}),
                
                PathClicks = pDataBasePath & "\" & pAccountName & "\Link_clicks.csv",
                SourceClicks = Csv.Document(File.Contents(PathClicks), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                #"HeadersClicks" = Table.PromoteHeaders(SourceClicks, [PromoteAllScalars=true]),
                #"TypeClicks" = Table.TransformColumnTypes(#"HeadersClicks",{{"Date", type date}, {"Clicks", Int64.Type}}),

                Merged = Table.NestedJoin(#"TypeVisits", {"Date"}, #"TypeClicks", {"Date"}, "ClicksTable", JoinKind.LeftOuter),
                Expanded = Table.ExpandTableColumn(Merged, "ClicksTable", {"Clicks"}, {"Clicks"}),
                ReplacedNulls = Table.ReplaceValue(Expanded, null, 0, Replacer.ReplaceValue, {"Clicks"})
            in
                ReplacedNulls
