table Calendario
	lineageTag: e5f6g7h8-0005
	dataCategory: Time

	column Data
		dataType: dateTime
		isKey
		formatString: dd/mm/yyyy
		lineageTag: c1c2c3c4-0010
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: c1c2c3c4-0011
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MesAno
		dataType: string
		lineageTag: c1c2c3c4-0012
		summarizeBy: none
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

	column DiaDaSemana
		dataType: string
		lineageTag: c1c2c3c4-0013
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
					StartDate = #date(2026, 1, 1),
					EndDate = Date.From(DateTime.LocalNow()),
					DayCount = Duration.Days(EndDate - StartDate) + 1,
					DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
					TableFromList = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
					Typed = Table.TransformColumnTypes(TableFromList, {{"Date", type date}}),
					AddYear = Table.AddColumn(Typed, "Year", each Date.Year([Date]), Int64.Type),
					AddMonthYear = Table.AddColumn(AddYear, "MonthYear", each Date.ToText([Date], "MMM/yyyy"), type text),
					AddDayOfWeek = Table.AddColumn(AddMonthYear, "DayOfWeek", each Date.ToText([Date], "dddd"), type text)
				in
					AddDayOfWeek

	annotation PBI_ResultType = Table

