table Interacoes
	lineageTag: e5f6g7h8-0002

	measure 'Total Interacoes' = SUM(Interacoes[Interacoes])
		formatString: #,##0
		lineageTag: m1m2m3m4-0003

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c1c2c3c4-0003
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Interacoes
		dataType: int64
		formatString: #,##0
		lineageTag: c1c2c3c4-0004
		summarizeBy: sum
		sourceColumn: Interactions

		annotation SummarizationSetBy = Automatic

	partition Interacoes = m
		mode: import
		source =
				let
					Path = pDataBasePath & "\" & pAccountName & "\Interactions.csv",
					Source = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Interactions", Int64.Type}})
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

