table Visitas_Cliques
	lineageTag: e5f6g7h8-0004

	measure 'Total Visitas ao Perfil' = SUM(Visitas_Cliques[Visitas])
		formatString: #,##0
		lineageTag: m1m2m3m4-0005

	measure 'Total Cliques no Link' = SUM(Visitas_Cliques[Clicks])
		formatString: #,##0
		lineageTag: m1m2m3m4-0006

	measure 'Taxa Conversao Bio %' = DIVIDE([Total Cliques no Link], [Total Visitas ao Perfil], 0)
		formatString: 0.00%
		lineageTag: m1m2m3m4-0007

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c1c2c3c4-0007
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Visitas
		dataType: int64
		formatString: #,##0
		lineageTag: c1c2c3c4-0008
		summarizeBy: sum
		sourceColumn: Visits

		annotation SummarizationSetBy = Automatic

	column Clicks
		dataType: double
		formatString: #,##0
		lineageTag: c1c2c3c4-0009
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

	partition Visitas_Cliques = m
		mode: import
		source =
				let
					PathVisits = pDataBasePath & "\" & pAccountName & "\Visits.csv",
					SourceVisits = Csv.Document(File.Contents(PathVisits), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
					HeadersVisits = Table.PromoteHeaders(SourceVisits, [PromoteAllScalars=true]),
					TypeVisits = Table.TransformColumnTypes(HeadersVisits,{{"Date", type date}, {"Visits", Int64.Type}}),
				
					PathClicks = pDataBasePath & "\" & pAccountName & "\Link_clicks.csv",
					SourceClicks = Csv.Document(File.Contents(PathClicks), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
					HeadersClicks = Table.PromoteHeaders(SourceClicks, [PromoteAllScalars=true]),
					TypeClicks = Table.TransformColumnTypes(HeadersClicks,{{"Date", type date}, {"Clicks", Int64.Type}}),
				
					Merged = Table.NestedJoin(TypeVisits, {"Date"}, TypeClicks, {"Date"}, "ClicksTable", JoinKind.LeftOuter),
					Expanded = Table.ExpandTableColumn(Merged, "ClicksTable", {"Clicks"}, {"Clicks"}),
					ReplacedNulls = Table.ReplaceValue(Expanded, null, 0, Replacer.ReplaceValue, {"Clicks"})
				in
					ReplacedNulls

	annotation PBI_ResultType = Table

